name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
          submodules: 'recursive'

      - name: Install extended Hugo (scss/saas)
        run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.deb -O hugo.deb
          sudo dpkg -i hugo.deb
          hugo version

      - name: Set up Node 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm install

      - name: Generate public site
        run: hugo

      - name: Deploy to Google AppEngine
        uses: google-github-actions/deploy-appengine@v0.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}